AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3 Bucket for application

Parameters:
  BucketName:
    Type: String
    Description: Name of the bucket

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${BucketName}-${AWS::Region}-${AWS::AccountId}

Outputs:
  S3BucketName:
    Description: Name of the s3 bucket
    Value: !Ref S3Bucket
