version = 0.1
[default.deploy.parameters]
stack_name = "consul-server-stack"
resolve_s3 = true
s3_prefix = "consul-server-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "BucketName=\"consul-bucket-us-east-2-704678691702\" ALBNamePrefix=\"consul-public\" ALBType=\"internet-facing\" VPCID=\"vpc-08b9de2cdfbc47241\" PrivateSubnets=\"subnet-0fe86dcff4cbcf188,subnet-0110b78504c16e39c,subnet-07cdb788d005535cc\" PublicSubnets=\"subnet-01b8359d5ed0d496a,subnet-0b66889977bc19182,subnet-0eff6779447cd26ce\" RequestTimeOut=\"60\" SSLCertificateARN=\"arn:aws:acm:us-east-2:704678691702:certificate/326c4d73-5e2e-4cd4-ab70-8c71c41d08e8\" DomainName=\"us-east-2.consul.proapplication.net\" HostedZoneId=\"Z0716017FNQSL38BA6TG\""

