AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Peer Routing

Parameters:
  VpcPeerConnectionId:
    Type: String
    Description: VPC Peer Connection ID

  PeerVpcCidr:
    Type: String
    Description: VPC Peer CIDR

  PrivateRouteTableId:
    Type: String
    Description: Local VPC Route Table ID

  PublicRouteTableId:
    Type: String
    Description: Local VPC Route Table ID

Resources:
  PeerVpcRoutePrivate:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref PeerVpcCidr
      RouteTableId: !Ref PrivateRouteTableId
      VpcPeeringConnectionId: !Ref VpcPeerConnectionId

  PeerVpcRoutePublic:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref PeerVpcCidr
      RouteTableId: !Ref PublicRouteTableId
      VpcPeeringConnectionId: !Ref VpcPeerConnectionId